In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
# importing numpy
import numpy as np

# Exercise 1

In [17]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
matrix = arr1.reshape(2,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Exercise 2

In [61]:
arr2 = np.arange(1,20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [77]:
extracted = arr2[4:14]
extracted

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Excercise 3

In [79]:
import pandas as pd

In [81]:
fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
fruits

apples     3
bananas    2
oranges    1
dtype: int64

In [85]:
fruits['pears'] = 4
fruits

apples     3
bananas    2
oranges    1
pears      4
dtype: int64

# Exercise 4

In [103]:
df = pd.DataFrame({'Name': ['John','Liya','Sam','Julia','Tony','Lissy','David','Anna','Peter','Martha'],'Age': [24,33,18,46,27,34,52,26,38,23],
'Gender': ['M','F','M','F','M','F','M','F','M','F']})
df

Name  Age Gender
0    John   24      M
1    Liya   33      F
2     Sam   18      M
3   Julia   46      F
4    Tony   27      M
5   Lissy   34      F
6   David   52      M
7    Anna   26      F
8   Peter   38      M
9  Martha   23      F

# Exercise 5

In [107]:
df['Occupation']=['Manager','Analyst','Programmer','Analyst','Analyst','Programmer','Programmer','Manager','Analyst','Programmer']
df

Name  Age Gender  Occupation
0    John   24      M     Manager
1    Liya   33      F     Analyst
2     Sam   18      M  Programmer
3   Julia   46      F     Analyst
4    Tony   27      M     Analyst
5   Lissy   34      F  Programmer
6   David   52      M  Programmer
7    Anna   26      F     Manager
8   Peter   38      M     Analyst
9  Martha   23      F  Programmer

# Exercise 6

In [114]:
# the age is greater than or equal to 30
df1 = df.loc[df['Age'] >= 30]
df1

Name  Age Gender  Occupation
1   Liya   33      F     Analyst
3  Julia   46      F     Analyst
5  Lissy   34      F  Programmer
6  David   52      M  Programmer
8  Peter   38      M     Analyst

# Exercise 7

In [139]:
df.to_csv('Company_data.csv',index = False)

In [141]:
df_from_csv = pd.read_csv('Company_data.csv')

In [143]:
df_from_csv

Name  Age Gender  Occupation
0    John   24      M     Manager
1    Liya   33      F     Analyst
2     Sam   18      M  Programmer
3   Julia   46      F     Analyst
4    Tony   27      M     Analyst
5   Lissy   34      F  Programmer
6   David   52      M  Programmer
7    Anna   26      F     Manager
8   Peter   38      M     Analyst
9  Martha   23      F  Programmer